//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceHost.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServiceHost.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos los estudiantes.
        /// </summary>
        public static string AllStudentsLabel {
            get {
                return ResourceManager.GetString("AllStudentsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar turno.
        /// </summary>
        public static string CancelShiftLabel {
            get {
                return ResourceManager.GetString("CancelShiftLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carrera.
        /// </summary>
        public static string CareerPlaceholder {
            get {
                return ResourceManager.GetString("CareerPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un tutor con ese número de personal..
        /// </summary>
        public static string DuplicateTutorFault_Message {
            get {
                return ResourceManager.GetString("DuplicateTutorFault_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tutor duplicado..
        /// </summary>
        public static string DuplicateTutorFault_Reason {
            get {
                return ResourceManager.GetString("DuplicateTutorFault_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        public static string EmailPlaceholder {
            get {
                return ResourceManager.GetString("EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingles.
        /// </summary>
        public static string EnglishLabel {
            get {
                return ResourceManager.GetString("EnglishLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error cancelando turno: {0}.
        /// </summary>
        public static string ErrorCancellingShift {
            get {
                return ResourceManager.GetString("ErrorCancellingShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error cargando carreras:.
        /// </summary>
        public static string ErrorLoadingCareers {
            get {
                return ResourceManager.GetString("ErrorLoadingCareers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error cargando carreras:.
        /// </summary>
        public static string ErrorLoadingCareers1 {
            get {
                return ResourceManager.GetString("ErrorLoadingCareers1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error cargando tutores:.
        /// </summary>
        public static string ErrorLoadingTutors {
            get {
                return ResourceManager.GetString("ErrorLoadingTutors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error cargando tutores:.
        /// </summary>
        public static string ErrorLoadingTutors1 {
            get {
                return ResourceManager.GetString("ErrorLoadingTutors1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error marcando como asistido: {0}.
        /// </summary>
        public static string ErrorMarkingAttended {
            get {
                return ResourceManager.GetString("ErrorMarkingAttended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error marcando como ausente: {0}.
        /// </summary>
        public static string ErrorMarkingNoShow {
            get {
                return ResourceManager.GetString("ErrorMarkingNoShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string ErrorTitle1 {
            get {
                return ResourceManager.GetString("ErrorTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string ErrorTitle2 {
            get {
                return ResourceManager.GetString("ErrorTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carrera.
        /// </summary>
        public static string Field_CbCareers {
            get {
                return ResourceManager.GetString("Field_CbCareers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tutor.
        /// </summary>
        public static string Field_CbTutors {
            get {
                return ResourceManager.GetString("Field_CbTutors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        public static string Field_TxtEmail {
            get {
                return ResourceManager.GetString("Field_TxtEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        public static string Field_TxtEmail1 {
            get {
                return ResourceManager.GetString("Field_TxtEmail1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Field_TxtFirstName {
            get {
                return ResourceManager.GetString("Field_TxtFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Field_TxtFirstName1 {
            get {
                return ResourceManager.GetString("Field_TxtFirstName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido materno.
        /// </summary>
        public static string Field_TxtMaternalSurname {
            get {
                return ResourceManager.GetString("Field_TxtMaternalSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido materno.
        /// </summary>
        public static string Field_TxtMaternalSurname1 {
            get {
                return ResourceManager.GetString("Field_TxtMaternalSurname1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string Field_TxtPassword {
            get {
                return ResourceManager.GetString("Field_TxtPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string Field_TxtPassword1 {
            get {
                return ResourceManager.GetString("Field_TxtPassword1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido paterno.
        /// </summary>
        public static string Field_TxtPaternalSurname {
            get {
                return ResourceManager.GetString("Field_TxtPaternalSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido paterno.
        /// </summary>
        public static string Field_TxtPaternalSurname1 {
            get {
                return ResourceManager.GetString("Field_TxtPaternalSurname1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        public static string Field_TxtPhone {
            get {
                return ResourceManager.GetString("Field_TxtPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Matrícula.
        /// </summary>
        public static string Field_TxtStudentId {
            get {
                return ResourceManager.GetString("Field_TxtStudentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID personal.
        /// </summary>
        public static string Field_TxtTutorId {
            get {
                return ResourceManager.GetString("Field_TxtTutorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string FirstNamePlaceholder {
            get {
                return ResourceManager.GetString("FirstNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desde:.
        /// </summary>
        public static string FromLabel {
            get {
                return ResourceManager.GetString("FromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desde:.
        /// </summary>
        public static string FromLabel1 {
            get {
                return ResourceManager.GetString("FromLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar.
        /// </summary>
        public static string GenerateButtonLabel {
            get {
                return ResourceManager.GetString("GenerateButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar.
        /// </summary>
        public static string GenerateButtonLabel1 {
            get {
                return ResourceManager.GetString("GenerateButtonLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TurnoId.
        /// </summary>
        public static string HeaderAppointmentId {
            get {
                return ResourceManager.GetString("HeaderAppointmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carrera.
        /// </summary>
        public static string HeaderCareer {
            get {
                return ResourceManager.GetString("HeaderCareer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string HeaderDate {
            get {
                return ResourceManager.GetString("HeaderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string HeaderDate1 {
            get {
                return ResourceManager.GetString("HeaderDate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string HeaderDate2 {
            get {
                return ResourceManager.GetString("HeaderDate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        public static string HeaderEmail {
            get {
                return ResourceManager.GetString("HeaderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        public static string HeaderEmail1 {
            get {
                return ResourceManager.GetString("HeaderEmail1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string HeaderFirstName {
            get {
                return ResourceManager.GetString("HeaderFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID.
        /// </summary>
        public static string HeaderID {
            get {
                return ResourceManager.GetString("HeaderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido materno.
        /// </summary>
        public static string HeaderMaternalSurname {
            get {
                return ResourceManager.GetString("HeaderMaternalSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Matrícula.
        /// </summary>
        public static string HeaderMatricula {
            get {
                return ResourceManager.GetString("HeaderMatricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Matrícula.
        /// </summary>
        public static string HeaderMatricula1 {
            get {
                return ResourceManager.GetString("HeaderMatricula1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string HeaderName {
            get {
                return ResourceManager.GetString("HeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido paterno.
        /// </summary>
        public static string HeaderPaternalSurname {
            get {
                return ResourceManager.GetString("HeaderPaternalSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        public static string HeaderPhone {
            get {
                return ResourceManager.GetString("HeaderPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Turno.
        /// </summary>
        public static string HeaderShiftId {
            get {
                return ResourceManager.GetString("HeaderShiftId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Turno.
        /// </summary>
        public static string HeaderShiftId1 {
            get {
                return ResourceManager.GetString("HeaderShiftId1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string HeaderStatus {
            get {
                return ResourceManager.GetString("HeaderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estudiante.
        /// </summary>
        public static string HeaderStudent {
            get {
                return ResourceManager.GetString("HeaderStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estudiante.
        /// </summary>
        public static string HeaderStudent1 {
            get {
                return ResourceManager.GetString("HeaderStudent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estudiante.
        /// </summary>
        public static string HeaderStudent2 {
            get {
                return ResourceManager.GetString("HeaderStudent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tutor.
        /// </summary>
        public static string HeaderTutor {
            get {
                return ResourceManager.GetString("HeaderTutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tutor.
        /// </summary>
        public static string HeaderTutor1 {
            get {
                return ResourceManager.GetString("HeaderTutor1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tutor.
        /// </summary>
        public static string HeaderTutor2 {
            get {
                return ResourceManager.GetString("HeaderTutor2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID.
        /// </summary>
        public static string HeaderTutorId {
            get {
                return ResourceManager.GetString("HeaderTutorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma:.
        /// </summary>
        public static string IdiomaLabel {
            get {
                return ResourceManager.GetString("IdiomaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información.
        /// </summary>
        public static string InfoTitle {
            get {
                return ResourceManager.GetString("InfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrar estudiantes.
        /// </summary>
        public static string ManageStudentsLabel {
            get {
                return ResourceManager.GetString("ManageStudentsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrar tutores.
        /// </summary>
        public static string ManageTutorsLabel {
            get {
                return ResourceManager.GetString("ManageTutorsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marcar asistido.
        /// </summary>
        public static string MarkAttendedLabel {
            get {
                return ResourceManager.GetString("MarkAttendedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marcar ausente.
        /// </summary>
        public static string MarkNoShowLabel {
            get {
                return ResourceManager.GetString("MarkNoShowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido materno.
        /// </summary>
        public static string MaternalSurnamePlaceholder {
            get {
                return ResourceManager.GetString("MaternalSurnamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La matrícula debe tener 2 letras y 8 dígitos..
        /// </summary>
        public static string Matricula_InvalidFormat {
            get {
                return ResourceManager.GetString("Matricula_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe especificar una matrícula..
        /// </summary>
        public static string Matricula_Required {
            get {
                return ResourceManager.GetString("Matricula_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Matrícula.
        /// </summary>
        public static string MatriculaPlaceholder {
            get {
                return ResourceManager.GetString("MatriculaPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar una carrera..
        /// </summary>
        public static string MustSelectCareer {
            get {
                return ResourceManager.GetString("MustSelectCareer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar un tutor y una carrera para el estudiante..
        /// </summary>
        public static string MustSelectTutorCareer {
            get {
                return ResourceManager.GetString("MustSelectTutorCareer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Value.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay turnos atendidos..
        /// </summary>
        public static string NoAppointmentsFound {
            get {
                return ResourceManager.GetString("NoAppointmentsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al procesar la notificación: {0}.
        /// </summary>
        public static string NotifyErrorMessageFormat {
            get {
                return ResourceManager.GetString("NotifyErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en notificación.
        /// </summary>
        public static string NotifyErrorTitle {
            get {
                return ResourceManager.GetString("NotifyErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu turno #{0} empieza pronto: {1}.
        /// </summary>
        public static string NotifyUpcomingMessageFormat {
            get {
                return ResourceManager.GetString("NotifyUpcomingMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recordatorio de turno.
        /// </summary>
        public static string NotifyUpcomingTitle {
            get {
                return ResourceManager.GetString("NotifyUpcomingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OK.
        /// </summary>
        public static string OKButtonText {
            get {
                return ResourceManager.GetString("OKButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe tener 8–20 caracteres, una mayúscula y un símbolo..
        /// </summary>
        public static string Password_InvalidFormat {
            get {
                return ResourceManager.GetString("Password_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe especificar una contraseña..
        /// </summary>
        public static string Password_Required {
            get {
                return ResourceManager.GetString("Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido paterno.
        /// </summary>
        public static string PaternalSurnamePlaceholder {
            get {
                return ResourceManager.GetString("PaternalSurnamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al generar PDF: {0}.
        /// </summary>
        public static string PdfGenerationError {
            get {
                return ResourceManager.GetString("PdfGenerationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione fecha de inicio y fin..
        /// </summary>
        public static string PleaseSelectBothDates {
            get {
                return ResourceManager.GetString("PleaseSelectBothDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imprimir.
        /// </summary>
        public static string PrintButtonLabel {
            get {
                return ResourceManager.GetString("PrintButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cola.
        /// </summary>
        public static string QueueTabHeader {
            get {
                return ResourceManager.GetString("QueueTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Motivo.
        /// </summary>
        public static string ReasonPlaceholder {
            get {
                return ResourceManager.GetString("ReasonPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe especificar una razón..
        /// </summary>
        public static string ReasonRequired {
            get {
                return ResourceManager.GetString("ReasonRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar cola.
        /// </summary>
        public static string RefreshQueueLabel {
            get {
                return ResourceManager.GetString("RefreshQueueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar estudiante.
        /// </summary>
        public static string RegisterStudentButtonLabel {
            get {
                return ResourceManager.GetString("RegisterStudentButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar estudiante.
        /// </summary>
        public static string RegisterStudentLabel {
            get {
                return ResourceManager.GetString("RegisterStudentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar estudiantes.
        /// </summary>
        public static string RegisterTabHeader {
            get {
                return ResourceManager.GetString("RegisterTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar tutor.
        /// </summary>
        public static string RegisterTutorButtonLabel {
            get {
                return ResourceManager.GetString("RegisterTutorButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Informe de turnos atendidos.
        /// </summary>
        public static string ReportsHeader {
            get {
                return ResourceManager.GetString("ReportsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Informe de turnos atendidos.
        /// </summary>
        public static string ReportsHeader1 {
            get {
                return ResourceManager.GetString("ReportsHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Informes.
        /// </summary>
        public static string ReportsLabel {
            get {
                return ResourceManager.GetString("ReportsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Turno cancelado..
        /// </summary>
        public static string ShiftCancelled {
            get {
                return ResourceManager.GetString("ShiftCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Turno marcado como asistido..
        /// </summary>
        public static string ShiftMarkedAttended {
            get {
                return ResourceManager.GetString("ShiftMarkedAttended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Turno marcado como ausente..
        /// </summary>
        public static string ShiftMarkedNoShow {
            get {
                return ResourceManager.GetString("ShiftMarkedNoShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        public static string SpanishLabel {
            get {
                return ResourceManager.GetString("SpanishLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha de inicio debe ser anterior a la de fin..
        /// </summary>
        public static string StartDateBeforeEndError {
            get {
                return ResourceManager.GetString("StartDateBeforeEndError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detener servidor.
        /// </summary>
        public static string StopServerLabel {
            get {
                return ResourceManager.GetString("StopServerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estudiante registrado con éxito..
        /// </summary>
        public static string StudentRegisteredSuccessfully {
            get {
                return ResourceManager.GetString("StudentRegisteredSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hasta:.
        /// </summary>
        public static string ToLabel {
            get {
                return ResourceManager.GetString("ToLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hasta:.
        /// </summary>
        public static string ToLabel1 {
            get {
                return ResourceManager.GetString("ToLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El ID de tutor debe iniciar con &apos;T&apos; mayúscula seguido de 3 dígitos..
        /// </summary>
        public static string TutorId_InvalidFormat {
            get {
                return ResourceManager.GetString("TutorId_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe especificar un ID de tutor..
        /// </summary>
        public static string TutorId_Required {
            get {
                return ResourceManager.GetString("TutorId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrar tutores.
        /// </summary>
        public static string TutorPageHeader {
            get {
                return ResourceManager.GetString("TutorPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tutor.
        /// </summary>
        public static string TutorPlaceholder {
            get {
                return ResourceManager.GetString("TutorPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tutor registrado con éxito..
        /// </summary>
        public static string TutorRegisteredSuccessfully {
            get {
                return ResourceManager.GetString("TutorRegisteredSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error inesperado: {0}.
        /// </summary>
        public static string UnexpectedErrorMessage {
            get {
                return ResourceManager.GetString("UnexpectedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error inesperado: {0}.
        /// </summary>
        public static string UnexpectedErrorMessage1 {
            get {
                return ResourceManager.GetString("UnexpectedErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu turno #{0} empieza pronto: {1}.
        /// </summary>
        public static string UpcomingAppointmentMessage {
            get {
                return ResourceManager.GetString("UpcomingAppointmentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recordatorio de turno.
        /// </summary>
        public static string UpcomingAppointmentTitle {
            get {
                return ResourceManager.GetString("UpcomingAppointmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de validación.
        /// </summary>
        public static string ValidationErrorTitle {
            get {
                return ResourceManager.GetString("ValidationErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de validación.
        /// </summary>
        public static string ValidationErrorTitle1 {
            get {
                return ResourceManager.GetString("ValidationErrorTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña requerida..
        /// </summary>
        public static string Validators_Password_Required {
            get {
                return ResourceManager.GetString("Validators.Password_Required", resourceCulture);
            }
        }
    }
}
