//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turnos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Turnos()
        {
            this.TurnoAbandonos = new HashSet<TurnoAbandonos>();
            this.TurnoCancelaciones = new HashSet<TurnoCancelaciones>();
        }
    
        public int TurnoId { get; set; }
        public string Matricula { get; set; }
        public string NumeroPersonal { get; set; }
        public int TutoriaId { get; set; }
        public int EstadoId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TurnoAbandonos> TurnoAbandonos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TurnoCancelaciones> TurnoCancelaciones { get; set; }
        public virtual TurnoEstados TurnoEstados { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Tutores Tutores { get; set; }
        public virtual Tutorias Tutorias { get; set; }
    }
}
