//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TurnoCancelaciones
    {
        public int CancelacionId { get; set; }
        public int TurnoId { get; set; }
        public System.DateTime FechaCancelacion { get; set; }
        public System.TimeSpan HoraCancelacion { get; set; }
        public string Razon { get; set; }
    
        public virtual Turnos Turnos { get; set; }
    }
}
