//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TurnosTutoriasEntities : DbContext
    {
        public TurnosTutoriasEntities()
            : base("name=TurnosTutoriasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Carreras> Carreras { get; set; }
        public virtual DbSet<EvaluacionFinal> EvaluacionFinal { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TurnoAbandonos> TurnoAbandonos { get; set; }
        public virtual DbSet<TurnoCancelaciones> TurnoCancelaciones { get; set; }
        public virtual DbSet<TurnoEstados> TurnoEstados { get; set; }
        public virtual DbSet<Turnos> Turnos { get; set; }
        public virtual DbSet<Tutores> Tutores { get; set; }
        public virtual DbSet<Tutorias> Tutorias { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
