//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutoriasClient.TutoriasServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegisterTutorRequest", Namespace="http://schemas.datacontract.org/2004/07/ServiceContracts.DTOs")]
    [System.SerializableAttribute()]
    public partial class RegisterTutorRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaternalSurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaternalSurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TutorIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaternalSurname {
            get {
                return this.MaternalSurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.MaternalSurnameField, value) != true)) {
                    this.MaternalSurnameField = value;
                    this.RaisePropertyChanged("MaternalSurname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaternalSurname {
            get {
                return this.PaternalSurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.PaternalSurnameField, value) != true)) {
                    this.PaternalSurnameField = value;
                    this.RaisePropertyChanged("PaternalSurname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TutorId {
            get {
                return this.TutorIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TutorIdField, value) != true)) {
                    this.TutorIdField = value;
                    this.RaisePropertyChanged("TutorId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DuplicateTutorFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceContracts")]
    [System.SerializableAttribute()]
    public partial class DuplicateTutorFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegisterStudentRequest", Namespace="http://schemas.datacontract.org/2004/07/ServiceContracts.DTOs")]
    [System.SerializableAttribute()]
    public partial class RegisterStudentRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CareerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaternalSurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaternalSurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TutorIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CareerId {
            get {
                return this.CareerIdField;
            }
            set {
                if ((this.CareerIdField.Equals(value) != true)) {
                    this.CareerIdField = value;
                    this.RaisePropertyChanged("CareerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaternalSurname {
            get {
                return this.MaternalSurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.MaternalSurnameField, value) != true)) {
                    this.MaternalSurnameField = value;
                    this.RaisePropertyChanged("MaternalSurname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaternalSurname {
            get {
                return this.PaternalSurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.PaternalSurnameField, value) != true)) {
                    this.PaternalSurnameField = value;
                    this.RaisePropertyChanged("PaternalSurname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StudentId {
            get {
                return this.StudentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentIdField, value) != true)) {
                    this.StudentIdField = value;
                    this.RaisePropertyChanged("StudentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TutorId {
            get {
                return this.TutorIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TutorIdField, value) != true)) {
                    this.TutorIdField = value;
                    this.RaisePropertyChanged("TutorId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DuplicateStudentFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceContracts")]
    [System.SerializableAttribute()]
    public partial class DuplicateStudentFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CapacityFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceContracts")]
    [System.SerializableAttribute()]
    public partial class CapacityFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginRequest", Namespace="http://schemas.datacontract.org/2004/07/ServiceContracts.DTOs")]
    [System.SerializableAttribute()]
    public partial class LoginRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudentIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StudentId {
            get {
                return this.StudentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentIdField, value) != true)) {
                    this.StudentIdField = value;
                    this.RaisePropertyChanged("StudentId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticatedUserDto", Namespace="http://schemas.datacontract.org/2004/07/ServiceContracts.DTOs")]
    [System.SerializableAttribute()]
    public partial class AuthenticatedUserDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CareerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaternalSurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaternalSurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CareerId {
            get {
                return this.CareerIdField;
            }
            set {
                if ((this.CareerIdField.Equals(value) != true)) {
                    this.CareerIdField = value;
                    this.RaisePropertyChanged("CareerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaternalSurname {
            get {
                return this.MaternalSurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.MaternalSurnameField, value) != true)) {
                    this.MaternalSurnameField = value;
                    this.RaisePropertyChanged("MaternalSurname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaternalSurname {
            get {
                return this.PaternalSurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.PaternalSurnameField, value) != true)) {
                    this.PaternalSurnameField = value;
                    this.RaisePropertyChanged("PaternalSurname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TutorDto", Namespace="http://schemas.datacontract.org/2004/07/ServiceContracts.DTOs")]
    [System.SerializableAttribute()]
    public partial class TutorDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CurrentLoadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaternalSurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaternalSurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TutorIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrentLoad {
            get {
                return this.CurrentLoadField;
            }
            set {
                if ((this.CurrentLoadField.Equals(value) != true)) {
                    this.CurrentLoadField = value;
                    this.RaisePropertyChanged("CurrentLoad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaternalSurname {
            get {
                return this.MaternalSurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.MaternalSurnameField, value) != true)) {
                    this.MaternalSurnameField = value;
                    this.RaisePropertyChanged("MaternalSurname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaternalSurname {
            get {
                return this.PaternalSurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.PaternalSurnameField, value) != true)) {
                    this.PaternalSurnameField = value;
                    this.RaisePropertyChanged("PaternalSurname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TutorId {
            get {
                return this.TutorIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TutorIdField, value) != true)) {
                    this.TutorIdField = value;
                    this.RaisePropertyChanged("TutorId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDto", Namespace="http://schemas.datacontract.org/2004/07/ServiceContracts.DTOs")]
    [System.SerializableAttribute()]
    public partial class UserDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CareerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaternalSurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaternalSurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TutorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CareerId {
            get {
                return this.CareerIdField;
            }
            set {
                if ((this.CareerIdField.Equals(value) != true)) {
                    this.CareerIdField = value;
                    this.RaisePropertyChanged("CareerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaternalSurname {
            get {
                return this.MaternalSurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.MaternalSurnameField, value) != true)) {
                    this.MaternalSurnameField = value;
                    this.RaisePropertyChanged("MaternalSurname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaternalSurname {
            get {
                return this.PaternalSurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.PaternalSurnameField, value) != true)) {
                    this.PaternalSurnameField = value;
                    this.RaisePropertyChanged("PaternalSurname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TutorId {
            get {
                return this.TutorIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TutorIdField, value) != true)) {
                    this.TutorIdField = value;
                    this.RaisePropertyChanged("TutorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CareerDto", Namespace="http://schemas.datacontract.org/2004/07/ServiceContracts.DTOs")]
    [System.SerializableAttribute()]
    public partial class CareerDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CareerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CareerNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CareerId {
            get {
                return this.CareerIdField;
            }
            set {
                if ((this.CareerIdField.Equals(value) != true)) {
                    this.CareerIdField = value;
                    this.RaisePropertyChanged("CareerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CareerName {
            get {
                return this.CareerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CareerNameField, value) != true)) {
                    this.CareerNameField = value;
                    this.RaisePropertyChanged("CareerName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateAppointmentRequest", Namespace="http://schemas.datacontract.org/2004/07/ServiceContracts.DTOs")]
    [System.SerializableAttribute()]
    public partial class CreateAppointmentRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SessionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TutorIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SessionId {
            get {
                return this.SessionIdField;
            }
            set {
                if ((this.SessionIdField.Equals(value) != true)) {
                    this.SessionIdField = value;
                    this.RaisePropertyChanged("SessionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StudentId {
            get {
                return this.StudentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentIdField, value) != true)) {
                    this.StudentIdField = value;
                    this.RaisePropertyChanged("StudentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TutorId {
            get {
                return this.TutorIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TutorIdField, value) != true)) {
                    this.TutorIdField = value;
                    this.RaisePropertyChanged("TutorId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppointmentDto", Namespace="http://schemas.datacontract.org/2004/07/ServiceContracts.DTOs.ServiceContracts.DT" +
        "Os")]
    [System.SerializableAttribute()]
    public partial class AppointmentDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AppointmentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SessionDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan SessionEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessionNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan SessionStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TutorIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AppointmentId {
            get {
                return this.AppointmentIdField;
            }
            set {
                if ((this.AppointmentIdField.Equals(value) != true)) {
                    this.AppointmentIdField = value;
                    this.RaisePropertyChanged("AppointmentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SessionDate {
            get {
                return this.SessionDateField;
            }
            set {
                if ((this.SessionDateField.Equals(value) != true)) {
                    this.SessionDateField = value;
                    this.RaisePropertyChanged("SessionDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan SessionEnd {
            get {
                return this.SessionEndField;
            }
            set {
                if ((this.SessionEndField.Equals(value) != true)) {
                    this.SessionEndField = value;
                    this.RaisePropertyChanged("SessionEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionName {
            get {
                return this.SessionNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionNameField, value) != true)) {
                    this.SessionNameField = value;
                    this.RaisePropertyChanged("SessionName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan SessionStart {
            get {
                return this.SessionStartField;
            }
            set {
                if ((this.SessionStartField.Equals(value) != true)) {
                    this.SessionStartField = value;
                    this.RaisePropertyChanged("SessionStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StudentId {
            get {
                return this.StudentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentIdField, value) != true)) {
                    this.StudentIdField = value;
                    this.RaisePropertyChanged("StudentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StudentName {
            get {
                return this.StudentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentNameField, value) != true)) {
                    this.StudentNameField = value;
                    this.RaisePropertyChanged("StudentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TutorId {
            get {
                return this.TutorIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TutorIdField, value) != true)) {
                    this.TutorIdField = value;
                    this.RaisePropertyChanged("TutorId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FinalEvaluationRequest", Namespace="http://schemas.datacontract.org/2004/07/ServiceContracts.DTOs")]
    [System.SerializableAttribute()]
    public partial class FinalEvaluationRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char AttendanceStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SessionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TutorIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char AttendanceStatus {
            get {
                return this.AttendanceStatusField;
            }
            set {
                if ((this.AttendanceStatusField.Equals(value) != true)) {
                    this.AttendanceStatusField = value;
                    this.RaisePropertyChanged("AttendanceStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rating {
            get {
                return this.RatingField;
            }
            set {
                if ((this.RatingField.Equals(value) != true)) {
                    this.RatingField = value;
                    this.RaisePropertyChanged("Rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SessionId {
            get {
                return this.SessionIdField;
            }
            set {
                if ((this.SessionIdField.Equals(value) != true)) {
                    this.SessionIdField = value;
                    this.RaisePropertyChanged("SessionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StudentId {
            get {
                return this.StudentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentIdField, value) != true)) {
                    this.StudentIdField = value;
                    this.RaisePropertyChanged("StudentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TutorId {
            get {
                return this.TutorIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TutorIdField, value) != true)) {
                    this.TutorIdField = value;
                    this.RaisePropertyChanged("TutorId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TutoriasServiceReference.IUserService")]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/RegisterTutor", ReplyAction="http://tempuri.org/IUserService/RegisterTutorResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TutoriasClient.TutoriasServiceReference.DuplicateTutorFault), Action="http://tempuri.org/IUserService/RegisterTutorDuplicateTutorFaultFault", Name="DuplicateTutorFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceContracts")]
        void RegisterTutor(TutoriasClient.TutoriasServiceReference.RegisterTutorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/RegisterTutor", ReplyAction="http://tempuri.org/IUserService/RegisterTutorResponse")]
        System.Threading.Tasks.Task RegisterTutorAsync(TutoriasClient.TutoriasServiceReference.RegisterTutorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/RegisterStudent", ReplyAction="http://tempuri.org/IUserService/RegisterStudentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TutoriasClient.TutoriasServiceReference.DuplicateStudentFault), Action="http://tempuri.org/IUserService/RegisterStudentDuplicateStudentFaultFault", Name="DuplicateStudentFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceContracts")]
        [System.ServiceModel.FaultContractAttribute(typeof(TutoriasClient.TutoriasServiceReference.CapacityFault), Action="http://tempuri.org/IUserService/RegisterStudentCapacityFaultFault", Name="CapacityFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceContracts")]
        void RegisterStudent(TutoriasClient.TutoriasServiceReference.RegisterStudentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/RegisterStudent", ReplyAction="http://tempuri.org/IUserService/RegisterStudentResponse")]
        System.Threading.Tasks.Task RegisterStudentAsync(TutoriasClient.TutoriasServiceReference.RegisterStudentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/LoginUser", ReplyAction="http://tempuri.org/IUserService/LoginUserResponse")]
        TutoriasClient.TutoriasServiceReference.AuthenticatedUserDto LoginUser(TutoriasClient.TutoriasServiceReference.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/LoginUser", ReplyAction="http://tempuri.org/IUserService/LoginUserResponse")]
        System.Threading.Tasks.Task<TutoriasClient.TutoriasServiceReference.AuthenticatedUserDto> LoginUserAsync(TutoriasClient.TutoriasServiceReference.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetAvailableTutors", ReplyAction="http://tempuri.org/IUserService/GetAvailableTutorsResponse")]
        TutoriasClient.TutoriasServiceReference.TutorDto[] GetAvailableTutors();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetAvailableTutors", ReplyAction="http://tempuri.org/IUserService/GetAvailableTutorsResponse")]
        System.Threading.Tasks.Task<TutoriasClient.TutoriasServiceReference.TutorDto[]> GetAvailableTutorsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetAllUsers", ReplyAction="http://tempuri.org/IUserService/GetAllUsersResponse")]
        TutoriasClient.TutoriasServiceReference.UserDto[] GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetAllUsers", ReplyAction="http://tempuri.org/IUserService/GetAllUsersResponse")]
        System.Threading.Tasks.Task<TutoriasClient.TutoriasServiceReference.UserDto[]> GetAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetAllTutors", ReplyAction="http://tempuri.org/IUserService/GetAllTutorsResponse")]
        TutoriasClient.TutoriasServiceReference.TutorDto[] GetAllTutors();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetAllTutors", ReplyAction="http://tempuri.org/IUserService/GetAllTutorsResponse")]
        System.Threading.Tasks.Task<TutoriasClient.TutoriasServiceReference.TutorDto[]> GetAllTutorsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetAllCareers", ReplyAction="http://tempuri.org/IUserService/GetAllCareersResponse")]
        TutoriasClient.TutoriasServiceReference.CareerDto[] GetAllCareers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetAllCareers", ReplyAction="http://tempuri.org/IUserService/GetAllCareersResponse")]
        System.Threading.Tasks.Task<TutoriasClient.TutoriasServiceReference.CareerDto[]> GetAllCareersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : TutoriasClient.TutoriasServiceReference.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<TutoriasClient.TutoriasServiceReference.IUserService>, TutoriasClient.TutoriasServiceReference.IUserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void RegisterTutor(TutoriasClient.TutoriasServiceReference.RegisterTutorRequest request) {
            base.Channel.RegisterTutor(request);
        }
        
        public System.Threading.Tasks.Task RegisterTutorAsync(TutoriasClient.TutoriasServiceReference.RegisterTutorRequest request) {
            return base.Channel.RegisterTutorAsync(request);
        }
        
        public void RegisterStudent(TutoriasClient.TutoriasServiceReference.RegisterStudentRequest request) {
            base.Channel.RegisterStudent(request);
        }
        
        public System.Threading.Tasks.Task RegisterStudentAsync(TutoriasClient.TutoriasServiceReference.RegisterStudentRequest request) {
            return base.Channel.RegisterStudentAsync(request);
        }
        
        public TutoriasClient.TutoriasServiceReference.AuthenticatedUserDto LoginUser(TutoriasClient.TutoriasServiceReference.LoginRequest request) {
            return base.Channel.LoginUser(request);
        }
        
        public System.Threading.Tasks.Task<TutoriasClient.TutoriasServiceReference.AuthenticatedUserDto> LoginUserAsync(TutoriasClient.TutoriasServiceReference.LoginRequest request) {
            return base.Channel.LoginUserAsync(request);
        }
        
        public TutoriasClient.TutoriasServiceReference.TutorDto[] GetAvailableTutors() {
            return base.Channel.GetAvailableTutors();
        }
        
        public System.Threading.Tasks.Task<TutoriasClient.TutoriasServiceReference.TutorDto[]> GetAvailableTutorsAsync() {
            return base.Channel.GetAvailableTutorsAsync();
        }
        
        public TutoriasClient.TutoriasServiceReference.UserDto[] GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public System.Threading.Tasks.Task<TutoriasClient.TutoriasServiceReference.UserDto[]> GetAllUsersAsync() {
            return base.Channel.GetAllUsersAsync();
        }
        
        public TutoriasClient.TutoriasServiceReference.TutorDto[] GetAllTutors() {
            return base.Channel.GetAllTutors();
        }
        
        public System.Threading.Tasks.Task<TutoriasClient.TutoriasServiceReference.TutorDto[]> GetAllTutorsAsync() {
            return base.Channel.GetAllTutorsAsync();
        }
        
        public TutoriasClient.TutoriasServiceReference.CareerDto[] GetAllCareers() {
            return base.Channel.GetAllCareers();
        }
        
        public System.Threading.Tasks.Task<TutoriasClient.TutoriasServiceReference.CareerDto[]> GetAllCareersAsync() {
            return base.Channel.GetAllCareersAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TutoriasServiceReference.ITutoringService", CallbackContract=typeof(TutoriasClient.TutoriasServiceReference.ITutoringServiceCallback))]
    public interface ITutoringService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITutoringService/CreateAppointment", ReplyAction="http://tempuri.org/ITutoringService/CreateAppointmentResponse")]
        int CreateAppointment(TutoriasClient.TutoriasServiceReference.CreateAppointmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITutoringService/CreateAppointment", ReplyAction="http://tempuri.org/ITutoringService/CreateAppointmentResponse")]
        System.Threading.Tasks.Task<int> CreateAppointmentAsync(TutoriasClient.TutoriasServiceReference.CreateAppointmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITutoringService/GetPendingAppointments", ReplyAction="http://tempuri.org/ITutoringService/GetPendingAppointmentsResponse")]
        TutoriasClient.TutoriasServiceReference.AppointmentDto[] GetPendingAppointments();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITutoringService/GetPendingAppointments", ReplyAction="http://tempuri.org/ITutoringService/GetPendingAppointmentsResponse")]
        System.Threading.Tasks.Task<TutoriasClient.TutoriasServiceReference.AppointmentDto[]> GetPendingAppointmentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITutoringService/CancelAppointment", ReplyAction="http://tempuri.org/ITutoringService/CancelAppointmentResponse")]
        void CancelAppointment(int appointmentId, string reason);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITutoringService/CancelAppointment", ReplyAction="http://tempuri.org/ITutoringService/CancelAppointmentResponse")]
        System.Threading.Tasks.Task CancelAppointmentAsync(int appointmentId, string reason);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITutoringService/NoShowAppointment", ReplyAction="http://tempuri.org/ITutoringService/NoShowAppointmentResponse")]
        void NoShowAppointment(int appointmentId, string reason);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITutoringService/NoShowAppointment", ReplyAction="http://tempuri.org/ITutoringService/NoShowAppointmentResponse")]
        System.Threading.Tasks.Task NoShowAppointmentAsync(int appointmentId, string reason);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITutoringService/RegisterSession", ReplyAction="http://tempuri.org/ITutoringService/RegisterSessionResponse")]
        void RegisterSession(int appointmentId, System.DateTime date, System.TimeSpan startTime, System.TimeSpan endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITutoringService/RegisterSession", ReplyAction="http://tempuri.org/ITutoringService/RegisterSessionResponse")]
        System.Threading.Tasks.Task RegisterSessionAsync(int appointmentId, System.DateTime date, System.TimeSpan startTime, System.TimeSpan endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITutoringService/EvaluateAppointment", ReplyAction="http://tempuri.org/ITutoringService/EvaluateAppointmentResponse")]
        void EvaluateAppointment(TutoriasClient.TutoriasServiceReference.FinalEvaluationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITutoringService/EvaluateAppointment", ReplyAction="http://tempuri.org/ITutoringService/EvaluateAppointmentResponse")]
        System.Threading.Tasks.Task EvaluateAppointmentAsync(TutoriasClient.TutoriasServiceReference.FinalEvaluationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITutoringService/SubscribeForNotifications")]
        void SubscribeForNotifications(string studentId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITutoringService/SubscribeForNotifications")]
        System.Threading.Tasks.Task SubscribeForNotificationsAsync(string studentId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITutoringService/UnsubscribeFromNotifications")]
        void UnsubscribeFromNotifications(string studentId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITutoringService/UnsubscribeFromNotifications")]
        System.Threading.Tasks.Task UnsubscribeFromNotificationsAsync(string studentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITutoringService/FinishSession", ReplyAction="http://tempuri.org/ITutoringService/FinishSessionResponse")]
        void FinishSession(int appointmentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITutoringService/FinishSession", ReplyAction="http://tempuri.org/ITutoringService/FinishSessionResponse")]
        System.Threading.Tasks.Task FinishSessionAsync(int appointmentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITutoringService/GetAttendedAppointment", ReplyAction="http://tempuri.org/ITutoringService/GetAttendedAppointmentResponse")]
        TutoriasClient.TutoriasServiceReference.AppointmentDto[] GetAttendedAppointment(System.DateTime from, System.DateTime to);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITutoringService/GetAttendedAppointment", ReplyAction="http://tempuri.org/ITutoringService/GetAttendedAppointmentResponse")]
        System.Threading.Tasks.Task<TutoriasClient.TutoriasServiceReference.AppointmentDto[]> GetAttendedAppointmentAsync(System.DateTime from, System.DateTime to);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITutoringServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITutoringService/NotifyUpcomingAppointment")]
        void NotifyUpcomingAppointment(TutoriasClient.TutoriasServiceReference.AppointmentDto appointment);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITutoringServiceChannel : TutoriasClient.TutoriasServiceReference.ITutoringService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TutoringServiceClient : System.ServiceModel.DuplexClientBase<TutoriasClient.TutoriasServiceReference.ITutoringService>, TutoriasClient.TutoriasServiceReference.ITutoringService {
        
        public TutoringServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public TutoringServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public TutoringServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public TutoringServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public TutoringServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public int CreateAppointment(TutoriasClient.TutoriasServiceReference.CreateAppointmentRequest request) {
            return base.Channel.CreateAppointment(request);
        }
        
        public System.Threading.Tasks.Task<int> CreateAppointmentAsync(TutoriasClient.TutoriasServiceReference.CreateAppointmentRequest request) {
            return base.Channel.CreateAppointmentAsync(request);
        }
        
        public TutoriasClient.TutoriasServiceReference.AppointmentDto[] GetPendingAppointments() {
            return base.Channel.GetPendingAppointments();
        }
        
        public System.Threading.Tasks.Task<TutoriasClient.TutoriasServiceReference.AppointmentDto[]> GetPendingAppointmentsAsync() {
            return base.Channel.GetPendingAppointmentsAsync();
        }
        
        public void CancelAppointment(int appointmentId, string reason) {
            base.Channel.CancelAppointment(appointmentId, reason);
        }
        
        public System.Threading.Tasks.Task CancelAppointmentAsync(int appointmentId, string reason) {
            return base.Channel.CancelAppointmentAsync(appointmentId, reason);
        }
        
        public void NoShowAppointment(int appointmentId, string reason) {
            base.Channel.NoShowAppointment(appointmentId, reason);
        }
        
        public System.Threading.Tasks.Task NoShowAppointmentAsync(int appointmentId, string reason) {
            return base.Channel.NoShowAppointmentAsync(appointmentId, reason);
        }
        
        public void RegisterSession(int appointmentId, System.DateTime date, System.TimeSpan startTime, System.TimeSpan endTime) {
            base.Channel.RegisterSession(appointmentId, date, startTime, endTime);
        }
        
        public System.Threading.Tasks.Task RegisterSessionAsync(int appointmentId, System.DateTime date, System.TimeSpan startTime, System.TimeSpan endTime) {
            return base.Channel.RegisterSessionAsync(appointmentId, date, startTime, endTime);
        }
        
        public void EvaluateAppointment(TutoriasClient.TutoriasServiceReference.FinalEvaluationRequest request) {
            base.Channel.EvaluateAppointment(request);
        }
        
        public System.Threading.Tasks.Task EvaluateAppointmentAsync(TutoriasClient.TutoriasServiceReference.FinalEvaluationRequest request) {
            return base.Channel.EvaluateAppointmentAsync(request);
        }
        
        public void SubscribeForNotifications(string studentId) {
            base.Channel.SubscribeForNotifications(studentId);
        }
        
        public System.Threading.Tasks.Task SubscribeForNotificationsAsync(string studentId) {
            return base.Channel.SubscribeForNotificationsAsync(studentId);
        }
        
        public void UnsubscribeFromNotifications(string studentId) {
            base.Channel.UnsubscribeFromNotifications(studentId);
        }
        
        public System.Threading.Tasks.Task UnsubscribeFromNotificationsAsync(string studentId) {
            return base.Channel.UnsubscribeFromNotificationsAsync(studentId);
        }
        
        public void FinishSession(int appointmentId) {
            base.Channel.FinishSession(appointmentId);
        }
        
        public System.Threading.Tasks.Task FinishSessionAsync(int appointmentId) {
            return base.Channel.FinishSessionAsync(appointmentId);
        }
        
        public TutoriasClient.TutoriasServiceReference.AppointmentDto[] GetAttendedAppointment(System.DateTime from, System.DateTime to) {
            return base.Channel.GetAttendedAppointment(from, to);
        }
        
        public System.Threading.Tasks.Task<TutoriasClient.TutoriasServiceReference.AppointmentDto[]> GetAttendedAppointmentAsync(System.DateTime from, System.DateTime to) {
            return base.Channel.GetAttendedAppointmentAsync(from, to);
        }
    }
}
