//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Validators {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Validators() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Data.Resources.Validators", typeof(Validators).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a “Formato inválido o dominio no permitido.”.
        /// </summary>
        internal static string Email_InvalidFormat {
            get {
                return ResourceManager.GetString("Email_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a “No puede estar vacío.”.
        /// </summary>
        internal static string Email_Required {
            get {
                return ResourceManager.GetString("Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estudiante: {0}, Tutor: {1} @ {2:g}.
        /// </summary>
        internal static string InfoFormat {
            get {
                return ResourceManager.GetString("InfoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La matrícula debe tener 2 letras y 8 dígitos..
        /// </summary>
        internal static string Matricula_InvalidFormat {
            get {
                return ResourceManager.GetString("Matricula_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Matricula must be 2 letters followed by 8 digits..
        /// </summary>
        internal static string Matricula_InvalidFormat1 {
            get {
                return ResourceManager.GetString("Matricula_InvalidFormat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe especificar una matrícula..
        /// </summary>
        internal static string Matricula_Required {
            get {
                return ResourceManager.GetString("Matricula_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must provide a matricula..
        /// </summary>
        internal static string Matricula_Required1 {
            get {
                return ResourceManager.GetString("Matricula_Required1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a “Sólo letras y hasta 20 caracteres.”.
        /// </summary>
        internal static string Name_InvalidCharacters {
            get {
                return ResourceManager.GetString("Name_InvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a “No puede estar vacío.”.
        /// </summary>
        internal static string Name_Required {
            get {
                return ResourceManager.GetString("Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe tener 8–20 caracteres, una mayúscula y un símbolo..
        /// </summary>
        internal static string Password_InvalidFormat {
            get {
                return ResourceManager.GetString("Password_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe especificar una contraseña..
        /// </summary>
        internal static string Password_Required {
            get {
                return ResourceManager.GetString("Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a “Sólo hasta 10 dígitos numéricos.”.
        /// </summary>
        internal static string Phone_InvalidFormat {
            get {
                return ResourceManager.GetString("Phone_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a “No puede estar vacío.”.
        /// </summary>
        internal static string Phone_Required {
            get {
                return ResourceManager.GetString("Phone_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} ({1:d}) {2:HH:mm}–{3:HH:mm}.
        /// </summary>
        internal static string SessionInfoFormat {
            get {
                return ResourceManager.GetString("SessionInfoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} (Evaluado: {1:g}).
        /// </summary>
        internal static string SummaryFormat {
            get {
                return ResourceManager.GetString("SummaryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El ID de tutor debe iniciar con &apos;T&apos; mayúscula seguido de 3 dígitos..
        /// </summary>
        internal static string TutorId_InvalidFormat {
            get {
                return ResourceManager.GetString("TutorId_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe especificar un ID de tutor..
        /// </summary>
        internal static string TutorId_Required {
            get {
                return ResourceManager.GetString("TutorId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desconocido.
        /// </summary>
        internal static string UnknownStatus {
            get {
                return ResourceManager.GetString("UnknownStatus", resourceCulture);
            }
        }
    }
}
